### ISSUE TITLE
Issue with using --ref-fasta option with vcf2maf.pl

### ISSUE THREAD

**Issue by devonsv** [mskcc/vcf2maf#68] opened 2016-08-23 10:36 UTC
Hi,
I have a similar problem with using the vcf2maf convertor as the user with issue #53.
I am using --ref-fasta to reference a  GRCh37 fasta file and and input vcf files which include snv's only. No snv's are included in the .vep.vcf and the .maf files.
I recieve an error per snv: ... specified reference allele x does not match Ensembl reference allele...
Are there any known issues using the --ref-fasta option?
Thanks.

**Comment by ckandoth** [comment] 2016-08-23 12:31
Please provide a sample variant so I can reproduce.

**Comment by devonsv** [comment] 2016-08-23 17:26
I've realised I can rem the --check_ref in the vep command line for now. I'll close and re-open if I need to. Thanks.

**Comment by ckandoth** [comment] 2016-08-23 17:28
No please don't do that. All issues I've seen to date are related to something wrong in the input files. If you can give me a VCF line that creates this issue, I will help resolve it.

**Comment by devonsv** [comment] 2016-08-24 10:24
OK thanks, as you say the issue doesn't appear to be with the vcf2maf script. Please see an example vcf line attached; it appears to be annotated correctly in the maf file when the check_ref option isn't used.

[test_line.txt](https://github.com/mskcc/vcf2maf/files/434492/test_line.txt)

**Comment by ckandoth** [comment] 2016-08-24 20:17
Thanks very much for the test VCF. It uses chr-prefix for chromosome names, indicating that it was generated using either UCSC's hg19 or NCBI's GRCh37.p13 as [explained here](https://www.biostars.org/p/119295/#119308)

The GRCh37 fasta you used with `--ref-fasta`, does not use chr-prefixes, so VEP was unable to lookup the "chr1:966125" locus, and gave you a warning. However, it continues with annotation, which runs properly.

The appropriate fix for this is to specify the correct reference fasta in `--ref-fasta` - use the same one that was used to generate the VCF you have. My guess is that it was hg19. You command would look like this:

```
perl vcf2maf.pl --input-vcf test_line.vcf --output-maf test_line.vep.maf --ref-fasta /path/to/hg19.fasta
```

**Closed by ckandoth** 2016-08-24 20:17 UTC

**Comment by devonsv** [comment] 2016-08-25 14:58
Many thanks for this.  Unfortunately the path to the reference fasta as commented in the vcf files no longer exists, but the tip regaring chrM and MT is helpful as this suggests hg19. I am now using an hg19 reference fasta and am getting less warnings, although still about half of the vcf lines in my sample file generate a warning.

(VEP doesn't write any annotation to the .vep.vcf file for lines in the original .vcf file that generate a warning. It only writes the annotation if --check-ref isn't used.)

**Comment by ckandoth** [comment] 2016-08-25 16:09
Thanks. Are you sure you're using vcf2maf v1.6.7? And with VEP v84 or v85.

**Comment by devonsv** [comment] 2016-08-25 16:26
I am using vcf2maf v1.6.7 but with an older version of VEP v78 which I need to keep. Sorry, I had assumed that  the vcf2maf was backwardly compatible. Looks like I should install vcf2maf v1.5.1. Thanks.

**Comment by ckandoth** [comment] 2016-08-25 16:31
I'd recommend installing VEP v84 or v85. There have been lots of bug fixes to VEP since v78. You can use the instructions in this gist - https://gist.github.com/ckandoth/57d189f018b448774704d3b2191720a6

**Comment by ckandoth** [comment] 2016-08-25 16:33
Note that if your input is GRCh37, the transcript database hasn't been updated since VEP v75. So you'll take advantage of the bug fixes, with no major upheaval of the underlying transcriptome.

**Comment by devonsv** [comment] 2016-08-25 16:57
Thanks very much for your help. I now have this working.

**Comment by ckandoth** [comment] 2016-08-25 17:16
No worries. In issue #38, I'm making vcf2maf do the reference checks using samtools, instead of leaving the responsibility to VEP. This gives us more control to report what's really going on, and what to do about it.
