### ISSUE TITLE
dbSNP field is not kept

### ISSUE THREAD

**Issue by Anahit19** [mskcc/vcf2maf#286] opened 2021-05-31 18:59 UTC
Hi,

I am running vcftomaf in a --inhibit-vep mode.

However, the dbsnp field is missed in the output and all the variants are represented as "novel" even if they were annotated in the corresponding vep.vcf file.

Could you please help with this issue. Thanks!

**Comment by ckandoth** [comment] 2021-06-16 15:03
When you run in `--inhibit-vep` mode, then vcf2maf depends on the contents of your input VCF. If dbSNP field is not named or formatted as in VEP-annotated VCFs, then it will not extract it correctly. If this is the case, then try again with VEP uninhibited. If not the case, then provide a test VCF so I can troubleshoot.

**Comment by Anahit19** [comment] 2021-06-18 07:36
Already fixed that issue. Thank you!

Just one problem that I have. Only for one vcf file for one chromosome of one of my samples I have the following issue while running vcf2maf:

 perl vcf2maf.pl --input-vcf BYZ01.vcf --output-maf BYZ01_check.vcf.maf --tumor-id BYZ01 --ref-fasta /gpfs/space/home/anahit/Genome_ref/GRCh38_bundle_GATK/resources_broad_hg38_v0_Homo_sapiens_assembly38.fasta --vep-path /gpfs/software/soft/manual/any/ensembl-vep/102/ --vep-data Consolidate_VCF/all_samples_all_chr_final/ --ncbi-build GRCh38 --vep-overwrite
STATUS: Running VEP and writing to: /Consolidate_vcf_snp/chr10/vcf2maf/BYZ01.vep.vcf
substr outside of string at /gpfs/software/soft/manual/any/ensembl-vep/102/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm line 906.
Died in forked process 33493

ERROR: Failed to run the VEP annotator! Command: /gpfs/software/soft/rocket/linux-centos7-x86_64/gcc-9.2.0/perl-5.32.0-p4hawuvj2bkzlo4bsu2zpd2lbs7fqsq5/bin/perl /gpfs/software/soft/manual/any/ensembl-vep/102//vep --species homo_sapiens --assembly GRCh38 --no_progress --no_stats --buffer_size 5000 --sift b --ccds --uniprot --hgvs --symbol --numbers --domains --gene_phenotype --canonical --protein --biotype --uniprot --tsl --variant_class --shift_hgvs 1 --check_existing --total_length --allele_number --no_escape --xref_refseq --failed 1 --vcf --flag_pick_allele --pick_order canonical,tsl,biotype,rank,ccds,length --dir Consolidate_VCF/all_samples_all_chr_final/ --fasta /gpfs/space/home/anahit/Genome_ref/GRCh38_bundle_GATK/resources_broad_hg38_v0_Homo_sapiens_assembly38.fasta --format vcf --input_file /Consolidate_vcf_snp/chr10/vcf2maf/BYZ01.vcf --output_file Consolidate_vcf_snp/chr10/vcf2maf/BYZ01.vep.vcf --force_overwrite --offline --pubmed --fork 4 --polyphen b --af --af_1kg --af_esp --af_gnomad --regulatory

**Comment by ckandoth** [comment] 2021-06-19 03:46
The error `substr outside of string at ...TranscriptVariationAllele.pm` implies there is something wrong in your input VCF. Please provide a sample VCF if you need help debugging.

**Comment by Anahit19** [comment] 2021-06-19 07:49
Thank you! Could you please give your email, so I can send it to you

**Comment by ckandoth** [comment] 2021-06-19 16:30
Sure. It's ckandoth on gmail.com.

**Comment by Anahit19** [comment] 2021-06-22 12:54
Hi. Did you receive my email?
Thank you!

**Comment by ckandoth** [comment] 2021-06-23 00:22
Thanks for sharing a VCF via email. The error is in VEP, and here is the specific variant that breaks it:
```bash
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
chr10	80081665	.	C	CAA,CA	.	PASS	.
```
I noticed that you reported this to the VEP authors, but they closed the issue assuming the error was in vcf2maf. I have opened a more detailed issue https://github.com/Ensembl/ensembl-vep/issues/1013 with details they can use to reproduce your issue. I will close this issue since it is not related to vcf2maf.

**Closed by ckandoth** 2021-06-23 00:22 UTC
