### ISSUE TITLE
WARNING: Specified reference allele does not match Ensembl reference allele on line 96

### ISSUE THREAD

**Issue by ggrimes** [mskcc/vcf2maf#78] opened 2016-09-16 15:05 UTC
I am getting an error when I run the latest version of vcf2maf.pl with latest version of VEP.

file:test.vep.vcf_warnings.txt
WARNING: Could not fetch sub-slice from 1:1249715-1249715(1) on line 96
WARNING: Specified reference allele C does not match Ensembl reference allele on line 96
WARNING: Could not fetch sub-slice from 1:1471220-1471220(1) on line 97
WARNING: Specified reference allele G does not match Ensembl reference allele on line 97
WARNING: Could not fetch sub-slice from 1:1670432-1670432(1) on line 98
WARNING: Specified reference allele T does not match Ensembl reference allele on line 98
WARNING: Could not fetch sub-slice from 1:11129576-11129576(1) on line 99
WARNING: Specified reference allele C does not match Ensembl reference allele on line 99
WARNING: Could not fetch sub-slice from 1:12907612-12907612(1) on line 100
WARNING: Specified reference allele A does not match Ensembl reference allele on line 100

Here is the command I ran
perl vcf2maf.pl \
--input-vcf test.vcf \
--output-maf $maf \
--tumor-id $tname \
--normal-id $nname \
--species homo_sapiens \
--vep-path $veppath \
--vep-data $vepdata \
--ref-fasta $reffa

Here is the test.vcf file 
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
1	1249715	.	C	T	.	PASS	SOMATIC;VT=SNP
1	1471220	.	G	A	.	PASS	SOMATIC;VT=SNP
1	1670432	.	T	C	.	PASS	SOMATIC;VT=SNP
1	11129576	rs367973268	C	T	.	PASS	DB;SOMATIC;VT=SNP
1	12907612	rs2994091	A	T	.	PASS	DB;SOMATIC;VT=SNP

Any help would be much appreciated.

Thanks

Graeme

**Comment by ckandoth** [comment] 2016-09-16 16:32
Your `test.vcf` worked fine with the latest release vcf2maf v1.6.8. Can you check if your `--ref-fasta` points to a reference genome that uses the same chromosome naming scheme as your FASTA file?

**Comment by vsvinti** [comment] 2016-09-19 16:13
Hi there

This is my first time running vcf2maf, I am having the exact same issue, except I am working with mouse data. I am using a vep version that is not install in my standard home directory. Even if I specify the custom vep-path and vep-data, it still looks in my home/.vep for a human genome reference file - is this expected behaviour? However, when I also give it the --ref-fasta, I get the error above (where all my variants are in the warnings file). 

This is true for both vcf2maf-1.6.8 and vcf2maf-master (downloaded today 19 Sep 2016). 

Command I am using is:
vcf2maf.pl --input-vcf $ngs_vcf_dir/$file.allchr.vcf \
--output-maf $ngs_maf_dir/$file.maf \
--tumor-id TUMOR --normal-id NORMAL \
--vep-path $ngs_vep_dir --vep-data $cache_dir \
--species mus_musculus --ncbi-build GRCm38 --ref-fasta $ngs_reference_seq 

And vcf is output of mutect2 from gatk:
<pre>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	TUMOR	NORMAL
1	3044607	.	C	CT	.	t_lod_fstar	ECNT=2;HCNT=1;MAX_ED=2;MIN_ED=2;NLOD=3.34;RPA=1,2;RU=T;STR;TLOD=4.23	GT:AD:AF:ALT_F1R2:ALT_F2R1:PGT:PID:QSS:REF_F1R2:REF_
F2R1	0/1:27,20:0.422:10:10:0|1:3044607_C_CT:897,653:8:19	0/0:34,12:0.255:8:4:0|1:3044607_C_CT:1138,392:16:18
1	3044609	.	C	CTTCTT	.	t_lod_fstar	ECNT=2;HCNT=1;MAX_ED=2;MIN_ED=2;NLOD=3.34;TLOD=4.23	GT:AD:AF:ALT_F1R2:ALT_F2R1:PGT:PID:QSS:REF_F1R2:REF_F2R1	0/1:
27,20:0.422:10:10:0|1:3044607_C_CT:809,646:8:19	0/0:36,12:0.255:8:4:0|1:3044607_C_CT:1116,365:16:20
</pre>

Any ideas on solutions are most welcome.  Thanks!

**Comment by vsvinti** [comment] 2016-09-20 12:20
Alternatively, I can run VEP separately (as this seems to work well), is it possible to run vcf2maf using this independently generated file?

**Comment by vsvinti** [comment] 2016-09-20 15:13
Update : I got this to work by running VEP independently, with the options specified by vcf2maf. It detects if there is an existing .vep.vcf file, and uses that instead of re-running vep. However, the vep integration in vcf2maf seems to be problematic.

**Comment by ggrimes** [comment] 2016-09-21 16:33
Thanks, for the quick response.

The ref fasta sequence points to the same fasta file that was used to generate the vcf file (using mutect1).

**Comment by ckandoth** [comment] 2016-09-21 17:12
@vsvinti I suspect the problem with GRCm38 is different. And something I'll troubleshoot in a bit.

@ggrimes Here is the command I ran successfully with vcf2maf v1.6.8 on your list of test variants. Can you try the same?
```bash
/opt/common/CentOS_6-dev/perl/perl-5.22.0/bin/perl \
    /opt/common/CentOS_6-dev/vcf2maf/v1.6.8/vcf2maf.pl \
    --input-vcf test.vcf \
    --output-maf test.vep.maf \
    --tumor-id TUMOR \
    --normal-id NORMAL \
    --species homo_sapiens \
    --vep-path /opt/common/CentOS_6-dev/vep/v85 \
    --vep-data /opt/common/CentOS_6-dev/vep/v85 \
    --ref-fasta /opt/common/CentOS_6-dev/vep/v85/homo_sapiens/85_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz
```

And the contents of `test.vcf`:
```bash
##fileformat=VCFv4.2
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
1	1249715	.	C	T	.	PASS	SOMATIC;VT=SNP
1	1471220	.	G	A	.	PASS	SOMATIC;VT=SNP
1	1670432	.	T	C	.	PASS	SOMATIC;VT=SNP
1	11129576	rs367973268	C	T	.	PASS	DB;SOMATIC;VT=SNP
1	12907612	rs2994091	A	T	.	PASS	DB;SOMATIC;VT=SNP
```

**Comment by ckandoth** [comment] 2016-09-21 17:17
@ggrimes Can you also make sure that VEP v85 is properly installed per the [instructions here](https://gist.github.com/ckandoth/176fe3199ed7cea682a68d438b8fdffb). The warnings generated may be indicating a missing Perl package responsible for reading FASTA files.

**Comment by ckandoth** [comment] 2016-09-22 01:12
@vsvinti I was able to run your sample VCF successfully with vcf2maf v1.6.8. Here is my command:
```bash
/opt/common/CentOS_6-dev/perl/perl-5.22.0/bin/perl \
    /opt/common/CentOS_6-dev/vcf2maf/v1.6.8/vcf2maf.pl \
    --input-vcf mouse.vcf \
    --output-maf mouse.vep.maf \
    --species mus_musculus \
    --ncbi-build GRCm38 \
    --vep-path /opt/common/CentOS_6-dev/vep/v85 \
    --vep-data /opt/common/CentOS_6-dev/vep/v85 \
    --ref-fasta /opt/common/CentOS_6-dev/vep/v85/mus_musculus/85_GRCm38/Mus_musculus.GRCm38.dna.primary_assembly.fa.gz
```

This is a sample VCF with your test variants:
```bash
##fileformat=VCFv4.2
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	TUMOR	NORMAL
1	3044607	.	C	CT	.	t_lod_fstar	ECNT=2;HCNT=1;MAX_ED=2;MIN_ED=2;NLOD=3.34;RPA=1,2;RU=T;STR;TLOD=4.23	GT:AD:AF:ALT_F1R2:ALT_F2R1:PGT:PID:QSS:REF_F1R2:REF_F2R1	0/1:27,20:0.422:10:10:0|1:3044607_C_CT:897,653:8:19	0/0:34,12:0.255:8:4:0|1:3044607_C_CT:1138,392:16:18
1	3044609	.	C	CTTCTT	.	t_lod_fstar	ECNT=2;HCNT=1;MAX_ED=2;MIN_ED=2;NLOD=3.34;TLOD=4.23	GT:AD:AF:ALT_F1R2:ALT_F2R1:PGT:PID:QSS:REF_F1R2:REF_F2R1	0/1:27,20:0.422:10:10:0|1:3044607_C_CT:809,646:8:19	0/0:36,12:0.255:8:4:0|1:3044607_C_CT:1116,365:16:20
```

Please let me know what you find from your tests. I'm going to leave this ticket open till I hear from both of you.

**Comment by ggrimes** [comment] 2016-09-26 11:13
The issue is with my  reference fa file.  
The fasta file I used has both upper and lower case nt (https://www.biostars.org/p/98042/).
When I change all nt in the fasta file to uppercase the issue disappears.

Thanks,

Graeme

**Comment by vsvinti** [comment] 2016-09-26 11:34
Hi there

I didn't get to the bottom of my problem, though I was using ensembl 83 not 85. 
However, I managed to run it as mentioned above, by running vep independently first, and vcf2maf was able to read that output. 

Thanks
Vicky

**Comment by ckandoth** [comment] 2016-09-29 17:27
@ggrimes @vsvinti I'm gonna close this ticket, but thanks much for the feedback.

**Closed by ckandoth** 2016-09-29 17:27 UTC
