### ISSUE TITLE
Annotate with GRCh38 error

### ISSUE THREAD

**Issue by pcheng84** [mskcc/vcf2maf#53] opened 2016-05-21 12:35 UTC
Hi Cyriac,
I'm having trouble running VCFs generated by Mutect2 and Haplotype caller aligned to GRCh38 with vcf2maf.

Running them through command line VEP is fine but when I try with vcf2maf using --ncbi-build GRCh38 it gives me this error.

WARNING: Could not fetch sub-slice from 1:632803-632803(1) on line 236
WARNING: Specified reference allele T does not match Ensembl reference allele on line 236
WARNING: Could not fetch sub-slice from 1:810105-810105(1) on line 237
WARNING: Specified reference allele C does not match Ensembl reference allele on line 237

The insertions are in the MAF file, but substitutions and deletions are not.

Cheers,
Phil

**Comment by ckandoth** [comment] 2016-06-02 18:40
Sorry for the late reply, Phil. Did you also change the default reference FASTA using `-ref-fasta`?

**Comment by pcheng84** [comment] 2016-06-07 07:29
Hi Cyriac,

I also tried it with the hg38 reference I used for alignment but it still skips the SNPs and just annotates the indels.

Cheers,
Phil

On Jun 2, 2016 20:40, Cyriac Kandoth <notifications@github.com> wrote:

Sorry for the late reply, Phil. Did you also change the default reference FASTA using -ref-fasta?

**Comment by ckandoth** [comment] 2016-06-09 20:21
can you give me a sample of your VCF?

**Comment by ckandoth** [comment] 2016-08-22 22:54
I'm going to close this issue, since I don't have enough data to reproduce.

**Closed by ckandoth** 2016-08-22 22:54 UTC
