### ISSUE TITLE
Problem running vcf2maf.pl script

### ISSUE THREAD

**Issue by raman91** [mskcc/vcf2maf#65] opened 2016-08-11 01:45 UTC
Hi,

I am trying to run the perl script vcf2maf.pl, but I am getting the following error:

ERROR: --regulatory is not available for this species at variant_effect_predictor.pl line 903.

Regards
Raman

**Comment by ckandoth** [comment] 2016-08-11 16:59
What species are you working with? The `--regulatory` option is only supported on some species.

**Comment by raman91** [comment] 2016-08-12 02:20
I am working with human

**Comment by ckandoth** [comment] 2016-08-12 04:08
Can you give me the command you used, and let me know how was VEP and it's cache installed

**Comment by ckandoth** [comment] 2016-08-22 20:07
I'm going to close this issue, since we don't have enough information to reproduce. Re-open if necessary.

**Comment by raman91** [comment] 2016-08-30 04:41
Sorry for the delay in response. 
I am running the command : 
perl vcf2maf.pl --input-vcf input.vcf --output-maf output.maf --tumor-id Tumor --normal-id Normal

I am getting 2 errors:
1. Failed to instantiate plugin ExAC: ERROR: ExAC file /home/nus/.vep/ExAC.r0.3.sites.minus_somatic.vcf.gz not found; you can download it from ftp://ftp.broadinstitute.org/pub/ExAC_release/current
When i go to the link, i only see ExAC.r0.3.1.sites.vep.vcf.gz which i have downloaded and placed it in the folder but i can't find ExAC.r0.3.sites.minus_somatic.vcf.gz .

2. ERROR: --regulatory is not available for this species at /home/nus/vep/variant_effect_predictor.pl line 903.

I am running the tool for human 

Thanks

Regards
Raman

**Comment by ckandoth** [comment] 2016-08-30 04:49
Raman, it sounds like VEP has not been installed by following the instructions [at this link](https://gist.github.com/ckandoth/176fe3199ed7cea682a68d438b8fdffb). Please review and confirm.

**Comment by raman91** [comment] 2016-08-31 10:05
Thank you cyriac. I had run the variant_effect_predictor.pl script and it was running. I will install again in that case

**Comment by ckandoth** [comment] 2016-08-31 15:09
Thanks Raman. In those [VEP installation instructions](https://gist.github.com/ckandoth/176fe3199ed7cea682a68d438b8fdffb), I changed the last command that tests if `variant_effect_predictor.pl` works... to match the way that vcf2maf runs it. So it should now be a better test for if VEP is installed properly with the ExAC plugin.

**Comment by raman91** [comment] 2016-09-01 02:54
Thank you cyriac
On testing VEP using the last command that tests if variant_effect_predictor.pl works. I am getting an ERROR: Cache directory --fasta/homo_sapiens not found.

**Comment by raman91** [comment] 2016-09-01 03:54
On running the command to handle VEP's Perl dependencies using cpanminus to install them under $PERL_PATH. I am getting an error:
curl: (77) error setting certificate verify locations:
CAfile: /etc/pki/tls/certs/ca-bundle.crt
CApath: none

**Comment by ckandoth** [comment] 2016-09-01 17:01
Raman, all these errors are unusual, and I need more information to figure out what's going on. Can you help me fill in these blanks:

1. Operating system you are using? e.g. Mac OSX, Linux, Windows, etc.?
2. Version of operating system? e.g. Mountain Lion, CentOS, Ubuntu, Windows 7
3. Output of running `perl --version` in command-line
4. What is the goal of your project? Are you sure `vcf2maf` is what you need?
5. Have you tried [VEP's online tool](http://grch37.ensembl.org/Homo_sapiens/Tools/VEP)?

**Comment by raman91** [comment] 2016-09-02 03:08
1. The operating system i am using is Linux
2. The version of the operating system is Ubuntu14.04
3. Output of running perl --version is perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux-gnu-thread-multi (with 44 registered patches)
4. I have to use a tool named maftools that takes maf file as a input. Since i have vcf files only. So, i wanted to convert the vcf files to maf files
5. I have tried the VEP's online tool and works good

Despite the error, i continued with the installation and was able to convert the example vcf file to maf file provided in the data/ folder. However, when i run on my data, i am getting an error : Segmentation fault (core dumped) and perl stopped unexpectedly . My computer RAM is pretty good (128GB)

Thank You

**Comment by raman91** [comment] 2016-09-02 11:39
I am able to run VEP, but i am not able to run vcf2maf.pl. It is showing me an error: Can't locate Bio/EnsEMBL/Variation/Utils/Sequence.pm in @INC

**Comment by ckandoth** [comment] 2016-09-22 01:32
Hi Raman. I'm unable to help you here. I apologize. I cannot reproduce any of the problems you're having. What's the latest problems you're experiencing?

**Comment by ckandoth** [comment] 2016-09-22 01:38
@raman91 It seems you've been having problems running vcf2maf since #47, which was mid-April. I am going to close this issue. Feel free to email me directly. My email address is [public here](https://github.com/ckandoth). And we can schedule a conference call with screen-sharing.

**Closed by ckandoth** 2016-09-22 01:38 UTC
